apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: it-helpdesk-data
  namespace: it-helpdesk
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 1Gi
