# Streamlit Secrets Template
# Copy this to .streamlit/secrets.toml for local development
# or add these secrets in Streamlit Cloud dashboard

[grok]
api_key = "your_grok_api_key_here"
api_url = "https://api.x.ai/v1"
model = "grok-beta"

# Example secrets structure for Streamlit Cloud:
# Go to your app dashboard > Settings > Secrets
# Add the following TOML content:

# GROK_API_KEY = "your_actual_api_key_here"
# GROK_API_URL = "https://api.x.ai/v1"
# GROK_MODEL = "grok-beta"
